### ISSUE TITLE
X2Go + Pano

### ISSUE THREAD

**Issue by simonero** [kmcgregor123456/CVNRimagingCore#16]
Pano froze Friday.  I wasn't running much (looking at T1s, a few remote terminals with nothing running, and had one reasonably sized trackvis file open), but I believe 3 users were logged in so there may have been more going on in actuality.  Since rebooting it manually (I was sitting at the machine) I also can't use X2Go.  I tried to X2Go remote into Pano while frozen before rebooting it, and was denied in the same way I would be if the machine was simply off.  I don't know if these things are related but temporally they coincided.  At minimum perhaps it would be a good idea to talk about Pano and how to avoid it crashing again?

I can still ssh from my mac terminal, but never in X2Go.  I've tried restarting Pano, the VMWare client, and my own computer.  I've tried to log in more times than I could count, from both Emory's wifi and my own.  I could use some help.  The error appears then disappears quickly, but I'll update this if I can get a screenshot...

Finally, when sshing into Pano, it seems a bit slow...  For example when nothing or minimal things are running, entering a cd command has a lag.

**Comment by kmcgregor123456** [comment]
Should work now

**Comment by simonero** [comment]
Not sure yet if configuration help will be needed (there are things that need to be changed in order for me to actually use it) but local X2Go does now allow login to pano.  Thank you.  Still unable to log onto qball1, qball4, or ralph, or to use VMWare to login per other open issue.

**Comment by kmcgregor123456** [comment]
This magically fixed itself after an X2Go server update. Should not have, but it now works...no root cause clearly identified.
